name: Release 

on: 
  push: 
    tags: 
      - v* 

jobs: 
  release: 
    runs-on: ubuntu-latest 

    steps: 
    - name: Check out Git repository 
      uses: actions/checkout@v2 

    - name: Setup Node.js environment 
      uses: actions/setup-node@v2 
      with: 
        node-version: '18' 

    - name: Install dependencies 
      run: npm install 

    - name: Build application 
      run: npm run dist 
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}





    - name: Release 
      uses: softprops/action-gh-release@v1 
      with: 
        files: dist/* 
      env: 
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

